name: medbook
description: "A new Flutter project."
publish_to: "none"

version: 1.0.2+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  flutter_html: ^3.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.3
  flutter_svg: ^2.2.0
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.1.3
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  internet_connection_checker: ^0.0.1+3
  carousel_slider: ^5.1.1
  flutter_social_button: ^1.1.3
  loading_animation_widget: ^1.2.0
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
  flutter_native_splash: ^2.4.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.18.1
  socket_io_client: ^3.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path_android: "lib/Assets/icons/medbook.png"
  image_path_ios: "lib/Assets/icons/medbook.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/final_splash.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  fonts:
    - family: Impact
      fonts:
        - asset: lib/Assets/font/impact.ttf

  assets:
    - lib/Assets/images/
    - lib/Assets/images/product_page2/
    - lib/Assets/images/Ads/
    - lib/Assets/icons/
    - lib/Assets/footer_icons/
    - assets/images/
